/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunar24.Vistas;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import vacunar24.Dao.CitaVacData;
import vacunar24.Dao.CiudadanoData;
import vacunar24.Dao.ProfesionalData;
import vacunar24.Dao.RegVacData;
import vacunar24.Dao.VacunaData;
import vacunar24.Entidades.CitaVacunacion;
import vacunar24.Entidades.Ciudadano;
import vacunar24.Entidades.RegistroVacunados;

/**
 *
 * @author Jose
 */
public class AgregarRegistro extends javax.swing.JDialog {

    private RegistroVacunados reg;
    private RegVacData rvd;
    private CitaVacData citaD;
    private CitaVacunacion cita;
    private ProfesionalData profD;
    private CiudadanoData cd;
    private VacunaData vd;
    private boolean mod;
    private boolean act;
    private int idMod;
    private int idProf;

    ;

    public AgregarRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        reg = new RegistroVacunados();
        rvd = new RegVacData();
        cita = new CitaVacunacion();
        citaD = new CitaVacData();
        cd = new CiudadanoData();
        mod = false;
        act = false;
        idMod=0;
        idProf=0;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTCentroVac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTProf = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jTCiud = new javax.swing.JTextField();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jTCod = new javax.swing.JTextField();
        jTNSerie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTVac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLT.setForeground(new java.awt.Color(51, 51, 51));
        jLT.setText("DATOS DEL REGISTRO");
        jPanel1.add(jLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 14, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("IdCiudadano:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Codigo Refuerzo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Centro de Vacunacion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Fecha de Colocacion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));
        jPanel1.add(jTCentroVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("N°SerieVacuna:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("IdProfesional");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jTProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProfActionPerformed(evt);
            }
        });
        jPanel1.add(jTProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, -1));

        jBLimpiar.setText("Limpiar Campos");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));
        jPanel1.add(jTCiud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));
        jPanel1.add(jDCFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, -1));

        jTCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodActionPerformed(evt);
            }
        });
        jPanel1.add(jTCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        jTNSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNSerieActionPerformed(evt);
            }
        });
        jPanel1.add(jTNSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("IdVacuna:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTVacActionPerformed(evt);
            }
        });
        jPanel1.add(jTVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            if (mod) {
                reg = rvd.buscarRegId(idMod);
                reg.setPersona(cd.buscarCiudadanoId(Integer.parseInt(jTCiud.getText())));
                reg.setCodRefuerzo(Integer.parseInt(jTCod.getText()));
                reg.setCentroVacunacion(jTCentroVac.getText());
                reg.setFechaHoraColoc(jDCFecha.toString());
                reg.setDosis(vd.buscarVacunaId(Integer.parseInt(jTVac.getText())));
                reg.setProf(colocaruncombox);
                rvd.modificarRegistro(reg);
                mod = false;
                act = true;
                dispose();
            } else {
                cita=citaD.buscarCitaId(idMod);
                reg.setPersona(cita.getPersona());
                reg.setCodRefuerzo(cita.getCodRefuerzo());
                reg.setCentroVacunacion(cita.getCentroVacunacion());
                reg.setFechaHoraColoc(LocalDateTime.now().toString());
                reg.setDosis(cita.getDosis());
                reg.setProf(profD.buscarProfesionalId(idProf));
                rvd.guardarRegVac(reg);
                act = true;
            }
            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos incompatible");
            limpiarCampos();
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Completar datos");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProfActionPerformed

    private void jTCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodActionPerformed

    private void jTNSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNSerieActionPerformed

    private void jTVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTVacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarRegistro dialog = new AgregarRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCentroVac;
    private javax.swing.JTextField jTCiud;
    private javax.swing.JTextField jTCod;
    private javax.swing.JTextField jTNSerie;
    private javax.swing.JTextField jTProf;
    private javax.swing.JTextField jTVac;
    // End of variables declaration//GEN-END:variables

    public void limpiarCampos() {

        jTNombre.setText("");
        jTApellido.setText("");
        jTDni.setText("");
        jTMail.setText("");
        jTCentroVac.setText("");
        jTProf.setText("");
        jTTel.setText("");
        jTPatolog.setText("");
        jCBAmbito.setSelectedIndex(-1);
        jCBProv.setSelectedIndex(-1);
        reg = null;

    }

    public javax.swing.JComboBox<String> getjCBAmbito() {
        return jCBAmbito;
    }

    public void setjCBAmbito(javax.swing.JComboBox<String> jCBAmbito) {
        this.jCBAmbito = jCBAmbito;
    }

    public javax.swing.JComboBox<String> getjCBProv() {
        return jCBProv;
    }

    public void setjCBProv(javax.swing.JComboBox<String> jCBProv) {
        this.jCBProv = jCBProv;
    }

    public javax.swing.JTextField getjTApellido() {
        return jTApellido;
    }

    public void setjTApellido(javax.swing.JTextField jTApellido) {
        this.jTApellido = jTApellido;
    }

    public javax.swing.JTextField getjTDni() {
        return jTDni;
    }

    public void setjTDni(javax.swing.JTextField jTDni) {
        this.jTDni = jTDni;
    }

    public javax.swing.JTextField getjTDom() {
        return jTProf;
    }

    public void setjTDom(javax.swing.JTextField jTDom) {
        this.jTProf = jTDom;
    }

    public javax.swing.JTextField getjTLocalidad() {
        return jTCentroVac;
    }

    public void setjTLocalidad(javax.swing.JTextField jTLocalidad) {
        this.jTCentroVac = jTLocalidad;
    }

    public javax.swing.JTextField getjTMail() {
        return jTMail;
    }

    public void setjTMail(javax.swing.JTextField jTMail) {
        this.jTMail = jTMail;
    }

    public javax.swing.JTextField getjTNombre() {
        return jTNombre;
    }

    public void setjTNombre(javax.swing.JTextField jTNombre) {
        this.jTNombre = jTNombre;
    }

    public javax.swing.JTextField getjTPatolog() {
        return jTPatolog;
    }

    public void setjTPatolog(javax.swing.JTextField jTPatolog) {
        this.jTPatolog = jTPatolog;
    }

    public javax.swing.JTextField getjTTel() {
        return jTTel;
    }

    public void setjTTel(javax.swing.JTextField jTTel) {
        this.jTTel = jTTel;
    }

    public boolean isMod() {
        return mod;
    }

    public void setMod(boolean mod) {
        this.mod = mod;
    }

    public boolean isAct() {
        return act;
    }

    public void setAct(boolean act) {
        this.act = act;
    }

    public int getIdMod() {
        return idMod;
    }

    public void setIdMod(int idMod) {
        this.idMod = idMod;
    }
    
}
