/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunar24.Vistas;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vacunar24.Dao.InsumoData;
import vacunar24.Dao.NotasData;
import vacunar24.Dao.ReporteData;
import vacunar24.Entidades.Insumos;
import vacunar24.Entidades.Notas;
import vacunar24.Entidades.Reporte;

/**
 *
 * @author Jose
 */
public class Home_Vista extends javax.swing.JInternalFrame {
    
    private Reporte rep;
    private ReporteData repD;
    private Insumos ins;
    private InsumoData insD;
    private ArrayList<Reporte> listaReportes;
    private ArrayList<Insumos> listaInsumos;
    private Notas nota;
    private NotasData notaD;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int row, int colum) {
            return false;
        }
    };
    private DefaultTableModel modelo1 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int colum) {
            return false;
        }
    };
    private Frame f = JOptionPane.getFrameForComponent(this);
    private ReporteVentana repV = new ReporteVentana(f, true);
    private InsumoVentana insV = new InsumoVentana(f, true);
    public Home_Vista() {
        rep = new Reporte();
        repD = new ReporteData();
        ins = new Insumos();
        insD = new InsumoData();
        listaReportes = new ArrayList();
        listaInsumos = new ArrayList();
        notaD = new NotasData();
        nota = notaD.traerNotas();
        initComponents();
        armarCabeceraIns();
        armarCabeceraRep();
        llenarTabla();
        llenarTablaIns();
        llenarNotas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRep = new javax.swing.JTable();
        jBEliminarRep = new javax.swing.JButton();
        jBEliminarIns = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTInsumos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTF1 = new javax.swing.JTextField();
        jTF2 = new javax.swing.JTextField();
        jTF3 = new javax.swing.JTextField();
        jTF4 = new javax.swing.JTextField();
        jTF5 = new javax.swing.JTextField();
        jTF6 = new javax.swing.JTextField();
        jTF7 = new javax.swing.JTextField();
        jBEnviarNotf = new javax.swing.JButton();
        jBElim = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 550));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(881, 350));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTRep.setFocusable(false);
        jTRep.getTableHeader().setResizingAllowed(false);
        jTRep.getTableHeader().setReorderingAllowed(false);
        jTRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTRepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTRep);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 380, 150));

        jBEliminarRep.setText("Eliminar");
        jBEliminarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarRepActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 470, 150, -1));

        jBEliminarIns.setText("Eliminar");
        jBEliminarIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarInsActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminarIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 250, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("REPORTES:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 200, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("NOTICIAS Y AVISOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 200, -1));

        jTInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTInsumos.setFocusable(false);
        jTInsumos.getTableHeader().setResizingAllowed(false);
        jTInsumos.getTableHeader().setReorderingAllowed(false);
        jTInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTInsumosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTInsumos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 380, 180));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jTF1.setText("                                                TITULO DEL AVISO");

        jBEnviarNotf.setText("Enviar");
        jBEnviarNotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarNotfActionPerformed(evt);
            }
        });

        jBElim.setText("Eliminar");
        jBElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBElimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jBEnviarNotf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBElim)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEnviarNotf)
                    .addComponent(jBElim))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 810, 440));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("PEDIDOS DE INSUMOS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 200, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
         actT();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jBEliminarInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarInsActionPerformed
        if (jTInsumos.getSelectedRow() >= 0) {
            insD.eliminarInsumo((int) jTInsumos.getValueAt(jTInsumos.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un Insumo en la tabla...");
        }
    }//GEN-LAST:event_jBEliminarInsActionPerformed

    private void jBEliminarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarRepActionPerformed
        if (jTRep.getSelectedRow() >= 0) {
            repD.eliminarReporte((int) jTRep.getValueAt(jTRep.getSelectedRow(), 0));
            actT();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un Reporte en la tabla...");
        }
    }//GEN-LAST:event_jBEliminarRepActionPerformed

    private void jBEnviarNotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarNotfActionPerformed
        String n1 = jTF1.getText();
        String n2 = jTF2.getText();
        String n3 = jTF3.getText();
        String n4 = jTF4.getText();
        String n5 = jTF5.getText();
        String n6 = jTF6.getText();
        String n7 = jTF7.getText();
        nota = new Notas (n1,n2,n3,n4,n5,n6,n7);
        notaD.eliminarNot();
        notaD.guardarNot(nota);
    }//GEN-LAST:event_jBEnviarNotfActionPerformed

    private void jBElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBElimActionPerformed
        notaD.eliminarNot();
    }//GEN-LAST:event_jBElimActionPerformed

    private void jTRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTRepMouseClicked
        if (jTRep.getSelectedRow() >= 0) {
            rep=repD.buscarRepId((int) jTRep.getValueAt(jTRep.getSelectedRow(),0));
            repD.revisarReporte(rep.getIdReporte());
            repV.getjLT().setText("REPORTE "+rep.getIdReporte());
            repV.getjTAsunto().setText(rep.getAsunto());
            repV.getjTDescr().setText(rep.getDescr());
            repV.getjLFech().setText(rep.getFech().toString());
            repV.show();
        }
    }//GEN-LAST:event_jTRepMouseClicked

    private void jTInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTInsumosMouseClicked
        if (jTInsumos.getSelectedRow() >= 0) {
            ins=insD.buscarInsumoId((int) jTInsumos.getValueAt(jTInsumos.getSelectedRow(),0));
            insV.getjLT().setText("PEDIDO INSUMO "+ins.getIdInsumo());
            insV.setId(ins.getIdInsumo());
            if(ins.getVac()!= null){
                insV.getjTVac().setText(ins.getVac().getMarca());
            }
            insV.getjTOtros().setText(ins.getOtros());
            insV.getjTAlcohol().setText(ins.getAlcohol()+"");
            insV.getjLFech().setText(ins.getFech().toString());
            insV.show();
        }
    }//GEN-LAST:event_jTInsumosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBElim;
    private javax.swing.JButton jBEliminarIns;
    private javax.swing.JButton jBEliminarRep;
    private javax.swing.JButton jBEnviarNotf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTextField jTF7;
    private javax.swing.JTable jTInsumos;
    private javax.swing.JTable jTRep;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraRep() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Codigo");
        filaCabecera.add("Asunto");
        filaCabecera.add("Descripcion");
        filaCabecera.add("Fecha de envio");
        filaCabecera.add("Revisado");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jTRep.setModel(modelo);

    }
    
    private void armarCabeceraIns() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Codigo");
        filaCabecera.add("Vacuna");
        filaCabecera.add("Otros");
        filaCabecera.add("Centro Vacunación");
        filaCabecera.add("Alcoholx5Ltrs");
        filaCabecera.add("Fecha");
        filaCabecera.add("Envio de insumo");
        for (Object it : filaCabecera) {
            modelo1.addColumn(it);
        }
        jTInsumos.setModel(modelo1);
    }
    
    private void llenarTabla() {
        listaReportes = repD.listarReportes();
        listaReportes.forEach(rep -> {
            modelo.addRow(new Object[]{rep.getIdReporte(), rep.getAsunto(), rep.getDescr(),
                 rep.getFech(), rep.isRev() ? "revisado" : "--"});
        });
    }
    
    private void llenarTablaIns() {
        listaInsumos = insD.listarInsumos();
        listaInsumos.forEach(ins -> {
            String vacuna = ins.getVac()!=null? ins.getVac().getMarca():"--";
            modelo1.addRow(new Object[]{ins.getIdInsumo(),vacuna, ins.getOtros(),ins.getCentroVacunacion()
                        ,ins.getAlcohol(),ins.getFech(),ins.isEnviado()?"Enviado":"--"});
        });
    }
    
    private void borrarFilas(){
        int i = jTRep.getRowCount()-1;
        for(;i>=0;i--){
            modelo.removeRow(i);
        }
    }
    private void borrarFilasIns(){
        int i = jTInsumos.getRowCount()-1;
        for(;i>=0;i--){
            modelo1.removeRow(i);
        }
    }
    private void actT(){
        borrarFilas();
        borrarFilasIns();
        llenarTabla();
        llenarTablaIns();
    }

    private void llenarNotas() {
        jTF1.setText(nota.getNot1());
        jTF2.setText(nota.getNot2());
        jTF3.setText(nota.getNot3());
        jTF4.setText(nota.getNot4());
        jTF5.setText(nota.getNot5());
        jTF6.setText(nota.getNot6());
        jTF7.setText(nota.getNot7());
    }

}
