/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunar24.Vistas;

import vacunar24.Dao.InsumoData;
import vacunar24.Entidades.Insumos;

/**
 *
 * @author Jose
 */
public class InsumoVentana extends javax.swing.JDialog {
    private Insumos ins;
    private InsumoData insD;
    private int id;
    public InsumoVentana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ins = new Insumos();
        insD = new InsumoData();
        id=0;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLT = new javax.swing.JLabel();
        jTVac = new javax.swing.JTextField();
        jLFech = new javax.swing.JLabel();
        jTAlcohol = new javax.swing.JTextField();
        jLDescr = new javax.swing.JLabel();
        jLAsunt = new javax.swing.JLabel();
        jLDescr1 = new javax.swing.JLabel();
        jTOtros = new javax.swing.JTextField();
        jLDescr2 = new javax.swing.JLabel();
        jTCentroVac = new javax.swing.JTextField();
        jBEnvio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLT.setForeground(new java.awt.Color(51, 51, 51));
        jLT.setText("PEDIDO INSUMO");
        jPanel1.add(jLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 200, -1));

        jTVac.setEditable(false);
        jPanel1.add(jTVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, -1));

        jLFech.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLFech.setForeground(new java.awt.Color(51, 51, 51));
        jLFech.setText("fecha");
        jPanel1.add(jLFech, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, -1));

        jTAlcohol.setEditable(false);
        jPanel1.add(jTAlcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 370, 30));

        jLDescr.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLDescr.setForeground(new java.awt.Color(51, 51, 51));
        jLDescr.setText("Alcohol x5 ltrs:");
        jPanel1.add(jLDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLAsunt.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLAsunt.setForeground(new java.awt.Color(51, 51, 51));
        jLAsunt.setText("Vacuna:");
        jPanel1.add(jLAsunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLDescr1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLDescr1.setForeground(new java.awt.Color(51, 51, 51));
        jLDescr1.setText("Otros:");
        jPanel1.add(jLDescr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jTOtros.setEditable(false);
        jPanel1.add(jTOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, 30));

        jLDescr2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLDescr2.setForeground(new java.awt.Color(51, 51, 51));
        jLDescr2.setText("Centro de Vacunación:");
        jPanel1.add(jLDescr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTCentroVac.setEditable(false);
        jPanel1.add(jTCentroVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 370, 30));

        jBEnvio.setText("Marcar como enviado");
        jBEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnvioActionPerformed(evt);
            }
        });
        jPanel1.add(jBEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnvioActionPerformed
        insD.NotifEnvio(id);
        
    }//GEN-LAST:event_jBEnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsumoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsumoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsumoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsumoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsumoVentana dialog = new InsumoVentana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEnvio;
    private javax.swing.JLabel jLAsunt;
    private javax.swing.JLabel jLDescr;
    private javax.swing.JLabel jLDescr1;
    private javax.swing.JLabel jLDescr2;
    private javax.swing.JLabel jLFech;
    private javax.swing.JLabel jLT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTAlcohol;
    private javax.swing.JTextField jTCentroVac;
    private javax.swing.JTextField jTOtros;
    private javax.swing.JTextField jTVac;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getjLFech() {
        return jLFech;
    }

    public void setjLFech(javax.swing.JLabel jLFech) {
        this.jLFech = jLFech;
    }

    public javax.swing.JLabel getjLT() {
        return jLT;
    }

    public void setjLT(javax.swing.JLabel jLT) {
        this.jLT = jLT;
    }

    public javax.swing.JTextField getjTAlcohol() {
        return jTAlcohol;
    }

    public void setjTAlcohol(javax.swing.JTextField jTAlcohol) {
        this.jTAlcohol = jTAlcohol;
    }

    public javax.swing.JTextField getjTCentroVac() {
        return jTCentroVac;
    }

    public void setjTCentroVac(javax.swing.JTextField jTCentroVac) {
        this.jTCentroVac = jTCentroVac;
    }

    public javax.swing.JTextField getjTOtros() {
        return jTOtros;
    }

    public void setjTOtros(javax.swing.JTextField jTOtros) {
        this.jTOtros = jTOtros;
    }

    public javax.swing.JTextField getjTVac() {
        return jTVac;
    }

    public void setjTVac(javax.swing.JTextField jTVac) {
        this.jTVac = jTVac;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
  
    
}
