/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunar24.Vistas;

import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author Jose
 */
public class MenuProf extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuProf() {
        initComponents();
        fecha();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPFondoCel = new javax.swing.JPanel();
        Escritorio = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLHome = new javax.swing.JLabel();
        jPanelTurno = new javax.swing.JPanel();
        jLTurno = new javax.swing.JLabel();
        jPanelCiudadano = new javax.swing.JPanel();
        jLCiudadano = new javax.swing.JLabel();
        jPanelProfesional = new javax.swing.JPanel();
        jLProfesional = new javax.swing.JLabel();
        jPanelVacuna = new javax.swing.JPanel();
        jLVacuna = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(90, 48));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(0, 51, 102));
        backgroundPanel.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1250, 450));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 153, 255)));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vacunar24/Imagenes/vacunar24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 70));

        jPFondoCel.setBackground(new java.awt.Color(51, 51, 51));
        jPFondoCel.setPreferredSize(new java.awt.Dimension(667, 320));

        Escritorio.setBackground(new java.awt.Color(153, 153, 153));
        Escritorio.setPreferredSize(new java.awt.Dimension(1024, 550));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        jPanelHome.setBackground(new java.awt.Color(0, 51, 102));
        jPanelHome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));
        jPanelHome.setForeground(new java.awt.Color(153, 153, 153));

        jLHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLHome.setForeground(new java.awt.Color(153, 153, 153));
        jLHome.setText("Inicio");
        jLHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLHome)
                .addGap(55, 55, 55))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLHome)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanelTurno.setBackground(new java.awt.Color(0, 51, 102));
        jPanelTurno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));
        jPanelTurno.setForeground(new java.awt.Color(153, 153, 153));

        jLTurno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTurno.setForeground(new java.awt.Color(153, 153, 153));
        jLTurno.setText("Registro Vacunados");
        jLTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTurnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLTurnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLTurnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelTurnoLayout = new javax.swing.GroupLayout(jPanelTurno);
        jPanelTurno.setLayout(jPanelTurnoLayout);
        jPanelTurnoLayout.setHorizontalGroup(
            jPanelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTurnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTurno)
                .addGap(16, 16, 16))
        );
        jPanelTurnoLayout.setVerticalGroup(
            jPanelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTurnoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLTurno)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanelCiudadano.setBackground(new java.awt.Color(0, 51, 102));
        jPanelCiudadano.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLCiudadano.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCiudadano.setForeground(new java.awt.Color(153, 153, 153));
        jLCiudadano.setText("Registrar un Paciente");
        jLCiudadano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCiudadanoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCiudadanoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCiudadanoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCiudadanoLayout = new javax.swing.GroupLayout(jPanelCiudadano);
        jPanelCiudadano.setLayout(jPanelCiudadanoLayout);
        jPanelCiudadanoLayout.setHorizontalGroup(
            jPanelCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiudadanoLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLCiudadano)
                .addGap(17, 17, 17))
        );
        jPanelCiudadanoLayout.setVerticalGroup(
            jPanelCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudadanoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLCiudadano)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelProfesional.setBackground(new java.awt.Color(0, 51, 102));
        jPanelProfesional.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLProfesional.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLProfesional.setForeground(new java.awt.Color(153, 153, 153));
        jLProfesional.setText("Insumos");
        jLProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProfesionalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLProfesionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLProfesionalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelProfesionalLayout = new javax.swing.GroupLayout(jPanelProfesional);
        jPanelProfesional.setLayout(jPanelProfesionalLayout);
        jPanelProfesionalLayout.setHorizontalGroup(
            jPanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfesionalLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLProfesional)
                .addGap(20, 20, 20))
        );
        jPanelProfesionalLayout.setVerticalGroup(
            jPanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfesionalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLProfesional)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanelVacuna.setBackground(new java.awt.Color(0, 51, 102));
        jPanelVacuna.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLVacuna.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLVacuna.setForeground(new java.awt.Color(153, 153, 153));
        jLVacuna.setText("Otros");
        jLVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLVacunaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLVacunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLVacunaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelVacunaLayout = new javax.swing.GroupLayout(jPanelVacuna);
        jPanelVacuna.setLayout(jPanelVacunaLayout);
        jPanelVacunaLayout.setHorizontalGroup(
            jPanelVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVacunaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVacuna)
                .addGap(51, 51, 51))
        );
        jPanelVacunaLayout.setVerticalGroup(
            jPanelVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVacunaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLVacuna)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPFondoCelLayout = new javax.swing.GroupLayout(jPFondoCel);
        jPFondoCel.setLayout(jPFondoCelLayout);
        jPFondoCelLayout.setHorizontalGroup(
            jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFondoCelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFondoCelLayout.createSequentialGroup()
                        .addGroup(jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelCiudadano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelTurno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPFondoCelLayout.createSequentialGroup()
                        .addGroup(jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelVacuna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPFondoCelLayout.setVerticalGroup(
            jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoCelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFondoCelLayout.createSequentialGroup()
                        .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanelVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPFondoCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1310, 680));

        jLFecha.setFont(new java.awt.Font("Corbel Light", 3, 24)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(153, 153, 153));
        jLFecha.setText("Fecha y Hora");
        backgroundPanel.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 240, 40));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCiudadanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCiudadanoMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Ciudadano_Vista cv = new Ciudadano_Vista();
        Escritorio.add(cv);
        cv.setVisible(true);
        cv.moveToFront();
    }//GEN-LAST:event_jLCiudadanoMouseClicked

    private void jLVacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVacunaMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Vacuna_Vista vac = new Vacuna_Vista();
        Escritorio.add(vac);
        vac.setVisible(true);
    }//GEN-LAST:event_jLVacunaMouseClicked

    private void jLProfesionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProfesionalMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Profesional_Vista prof = new Profesional_Vista();
        Escritorio.add(prof);
        prof.setVisible(true);
    }//GEN-LAST:event_jLProfesionalMouseClicked

    private void jLTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTurnoMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        CitaVac_Vista citaV = new CitaVac_Vista();
        Escritorio.add(citaV);
        citaV.setVisible(true);
    }//GEN-LAST:event_jLTurnoMouseClicked

    private void jLTurnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTurnoMouseEntered
        jPanelTurno.setBackground(new Color(51, 153, 255));
        jLTurno.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLTurnoMouseEntered

    private void jLTurnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTurnoMouseExited
        jPanelTurno.setBackground(new Color(0,51, 102));
        jLTurno.setForeground(new Color(153, 153, 153));

    }//GEN-LAST:event_jLTurnoMouseExited

    private void jLCiudadanoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCiudadanoMouseEntered
        jPanelCiudadano.setBackground(new Color(51, 153, 255));
        jLCiudadano.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLCiudadanoMouseEntered

    private void jLCiudadanoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCiudadanoMouseExited
        jPanelCiudadano.setBackground(new Color(0,51, 102));
        jLCiudadano.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLCiudadanoMouseExited

    private void jLProfesionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProfesionalMouseEntered
        jPanelProfesional.setBackground(new Color(51, 153, 255));
        jLProfesional.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLProfesionalMouseEntered

    private void jLProfesionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProfesionalMouseExited
        jPanelProfesional.setBackground(new Color(0,51, 102));
        jLProfesional.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLProfesionalMouseExited

    private void jLVacunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVacunaMouseEntered
        jPanelVacuna.setBackground(new Color(51, 153, 255));
        jLVacuna.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLVacunaMouseEntered

    private void jLVacunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVacunaMouseExited
        jPanelVacuna.setBackground(new Color(0,51, 102));
        jLVacuna.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLVacunaMouseExited

    private void jLHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHomeMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
    }//GEN-LAST:event_jLHomeMouseClicked

    private void jLHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHomeMouseEntered
        jPanelHome.setBackground(new Color(51, 153, 255));
        jLHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLHomeMouseEntered

    private void jLHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHomeMouseExited
        jPanelHome.setBackground(new Color(0,51, 102));
        jLHome.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLHomeMouseExited

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Escritorio;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel jLCiudadano;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLHome;
    private javax.swing.JLabel jLProfesional;
    private javax.swing.JLabel jLTurno;
    private javax.swing.JLabel jLVacuna;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPFondoCel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCiudadano;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelProfesional;
    private javax.swing.JPanel jPanelTurno;
    private javax.swing.JPanel jPanelVacuna;
    // End of variables declaration//GEN-END:variables

    public void fecha(){
        String mes="";
        switch(LocalDate.now().getMonthValue()){
            case 1: 
                   mes = "Enero";
                   break;
            case 2: 
                   mes = "Febrero";
                   break;
            case 3: 
                   mes = "Marzo";
                   break;
            case 4: 
                   mes = "Abril";
                   break;
            case 5: 
                   mes = "Mayo";
                   break;
            case 6: 
                   mes = "Junio";
                   break;
            case 7: 
                   mes = "Julio";
                   break;
            case 8: 
                   mes = "Agosto";
                   break;
            case 9: 
                   mes = "Septiembre";
                   break;
            case 10: 
                   mes = "Octubre";
                   break;
            case 11: 
                   mes = "Noviembre";
                   break;
            case 12: 
                   mes = "Diciembre";
                   break;        
        }
        String fech = LocalDate.now().getDayOfMonth()+" de "+mes+" del "+LocalDate.now().getYear();
        jLFecha.setText(fech);
    }
}
