/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunar24.Vistas;

import java.awt.Color;

/**
 *
 * @author Jose
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTurno = new javax.swing.JPanel();
        jLTurno = new javax.swing.JLabel();
        jPanelCiudadano = new javax.swing.JPanel();
        jLCiudadano = new javax.swing.JLabel();
        jPanelProfesional = new javax.swing.JPanel();
        jLProfesional = new javax.swing.JLabel();
        jPanelVacuna = new javax.swing.JPanel();
        jLVacuna = new javax.swing.JLabel();
        jPFondoCel = new javax.swing.JPanel();
        Escritorio = new javax.swing.JPanel();
        jPanelLaboratorio = new javax.swing.JPanel();
        jLLaboratorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(90, 48));
        setPreferredSize(new java.awt.Dimension(1320, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1250, 450));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 153, 255)));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vacunar24/Imagenes/vacunar24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        jPanelTurno.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTurno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));

        jLTurno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTurno.setForeground(new java.awt.Color(51, 153, 255));
        jLTurno.setText("Turnos");
        jLTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTurnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLTurnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLTurnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelTurnoLayout = new javax.swing.GroupLayout(jPanelTurno);
        jPanelTurno.setLayout(jPanelTurnoLayout);
        jPanelTurnoLayout.setHorizontalGroup(
            jPanelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTurnoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLTurno)
                .addGap(16, 16, 16))
        );
        jPanelTurnoLayout.setVerticalGroup(
            jPanelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTurnoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLTurno)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanelTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 110, -1));

        jPanelCiudadano.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCiudadano.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLCiudadano.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCiudadano.setForeground(new java.awt.Color(51, 153, 255));
        jLCiudadano.setText("Ciudadanos");
        jLCiudadano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCiudadanoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCiudadanoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCiudadanoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCiudadanoLayout = new javax.swing.GroupLayout(jPanelCiudadano);
        jPanelCiudadano.setLayout(jPanelCiudadanoLayout);
        jPanelCiudadanoLayout.setHorizontalGroup(
            jPanelCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiudadanoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLCiudadano)
                .addContainerGap())
        );
        jPanelCiudadanoLayout.setVerticalGroup(
            jPanelCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudadanoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLCiudadano)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanelCiudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 130, 70));

        jPanelProfesional.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProfesional.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLProfesional.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLProfesional.setForeground(new java.awt.Color(51, 153, 255));
        jLProfesional.setText("Profesional");
        jLProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProfesionalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLProfesionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLProfesionalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelProfesionalLayout = new javax.swing.GroupLayout(jPanelProfesional);
        jPanelProfesional.setLayout(jPanelProfesionalLayout);
        jPanelProfesionalLayout.setHorizontalGroup(
            jPanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfesionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProfesional)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelProfesionalLayout.setVerticalGroup(
            jPanelProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfesionalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLProfesional)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanelProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 110, 70));

        jPanelVacuna.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVacuna.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLVacuna.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLVacuna.setForeground(new java.awt.Color(51, 153, 255));
        jLVacuna.setText("Vacuna");
        jLVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLVacunaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLVacunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLVacunaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelVacunaLayout = new javax.swing.GroupLayout(jPanelVacuna);
        jPanelVacuna.setLayout(jPanelVacunaLayout);
        jPanelVacunaLayout.setHorizontalGroup(
            jPanelVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVacunaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLVacuna)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelVacunaLayout.setVerticalGroup(
            jPanelVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVacunaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLVacuna)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanelVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 120, 70));

        jPFondoCel.setBackground(new java.awt.Color(51, 153, 255));
        jPFondoCel.setPreferredSize(new java.awt.Dimension(667, 320));

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));
        Escritorio.setPreferredSize(new java.awt.Dimension(1024, 550));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1304, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPFondoCelLayout = new javax.swing.GroupLayout(jPFondoCel);
        jPFondoCel.setLayout(jPFondoCelLayout);
        jPFondoCelLayout.setHorizontalGroup(
            jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoCelLayout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFondoCelLayout.setVerticalGroup(
            jPFondoCelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoCelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPFondoCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1310, 700));

        jPanelLaboratorio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLaboratorio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLLaboratorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLLaboratorio.setForeground(new java.awt.Color(51, 153, 255));
        jLLaboratorio.setText("Laboratorios");
        jLLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLaboratorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLLaboratorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLLaboratorioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelLaboratorioLayout = new javax.swing.GroupLayout(jPanelLaboratorio);
        jPanelLaboratorio.setLayout(jPanelLaboratorioLayout);
        jPanelLaboratorioLayout.setHorizontalGroup(
            jPanelLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLaboratorioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLLaboratorio)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelLaboratorioLayout.setVerticalGroup(
            jPanelLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLaboratorioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLLaboratorio)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        backgroundPanel.add(jPanelLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 130, 70));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1300, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCiudadanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCiudadanoMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Ciudadano_Vista cv = new Ciudadano_Vista();
        Escritorio.add(cv);
        cv.setVisible(true);
        cv.moveToFront();
    }//GEN-LAST:event_jLCiudadanoMouseClicked

    private void jLVacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVacunaMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Vacuna_Vista vac = new Vacuna_Vista();
        Escritorio.add(vac);
        vac.setVisible(true);
    }//GEN-LAST:event_jLVacunaMouseClicked

    private void jLProfesionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProfesionalMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Profesional_Vista prof = new Profesional_Vista();
        Escritorio.add(prof);
        prof.setVisible(true);
    }//GEN-LAST:event_jLProfesionalMouseClicked

    private void jLLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLaboratorioMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        Laboratorio_Vista lab = new Laboratorio_Vista();
        Escritorio.add(lab);
        lab.setVisible(true);
    }//GEN-LAST:event_jLLaboratorioMouseClicked

    private void jLTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTurnoMouseClicked
        Escritorio.removeAll();
        Escritorio.repaint();
        CitaVac_Vista citaV = new CitaVac_Vista();
        Escritorio.add(citaV);
        citaV.setVisible(true);
    }//GEN-LAST:event_jLTurnoMouseClicked

    private void jLTurnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTurnoMouseEntered
        jPanelTurno.setBackground(new Color(51, 153, 255));
        jLTurno.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLTurnoMouseEntered

    private void jLTurnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTurnoMouseExited
        jPanelTurno.setBackground(Color.WHITE);
        jLTurno.setForeground(new Color(51, 153, 255));

    }//GEN-LAST:event_jLTurnoMouseExited

    private void jLCiudadanoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCiudadanoMouseEntered
        jPanelCiudadano.setBackground(new Color(51, 153, 255));
        jLCiudadano.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLCiudadanoMouseEntered

    private void jLCiudadanoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCiudadanoMouseExited
        jPanelCiudadano.setBackground(Color.WHITE);
        jLCiudadano.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_jLCiudadanoMouseExited

    private void jLProfesionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProfesionalMouseEntered
        jPanelProfesional.setBackground(new Color(51, 153, 255));
        jLProfesional.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLProfesionalMouseEntered

    private void jLProfesionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProfesionalMouseExited
        jPanelProfesional.setBackground(Color.WHITE);
        jLProfesional.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_jLProfesionalMouseExited

    private void jLVacunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVacunaMouseEntered
        jPanelVacuna.setBackground(new Color(51, 153, 255));
        jLVacuna.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLVacunaMouseEntered

    private void jLVacunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVacunaMouseExited
        jPanelVacuna.setBackground(Color.WHITE);
        jLVacuna.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_jLVacunaMouseExited

    private void jLLaboratorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLaboratorioMouseEntered
        jPanelLaboratorio.setBackground(new Color(51, 153, 255));
        jLLaboratorio.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLLaboratorioMouseEntered

    private void jLLaboratorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLaboratorioMouseExited
        jPanelLaboratorio.setBackground(Color.WHITE);
        jLLaboratorio.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_jLLaboratorioMouseExited

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Escritorio;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel jLCiudadano;
    private javax.swing.JLabel jLLaboratorio;
    private javax.swing.JLabel jLProfesional;
    private javax.swing.JLabel jLTurno;
    private javax.swing.JLabel jLVacuna;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPFondoCel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCiudadano;
    private javax.swing.JPanel jPanelLaboratorio;
    private javax.swing.JPanel jPanelProfesional;
    private javax.swing.JPanel jPanelTurno;
    private javax.swing.JPanel jPanelVacuna;
    // End of variables declaration//GEN-END:variables
}
