/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacunar24.Vistas;

import vacunar24.Dao.CiudadanoData;
import vacunar24.Dao.ReporteData;
import vacunar24.Entidades.Reporte;

/**
 *
 * @author Jose
 */
public class ReporteVentana extends javax.swing.JDialog {

    private Reporte rep;
    private ReporteData repD;
    

    public ReporteVentana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        rep = new Reporte();
        repD = new ReporteData();
        initComponents();
        llenarCampos();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLT = new javax.swing.JLabel();
        jTAsunto = new javax.swing.JTextField();
        jLFech = new javax.swing.JLabel();
        jTDescr = new javax.swing.JTextField();
        jLDescr = new javax.swing.JLabel();
        jLAsunt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLT.setForeground(new java.awt.Color(51, 51, 51));
        jLT.setText("REPORTE ");
        jPanel1.add(jLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 14, 180, -1));

        jTAsunto.setEditable(false);
        jPanel1.add(jTAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, -1));

        jLFech.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLFech.setForeground(new java.awt.Color(51, 51, 51));
        jLFech.setText("fecha");
        jPanel1.add(jLFech, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, -1));

        jTDescr.setEditable(false);
        jPanel1.add(jTDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 240));

        jLDescr.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLDescr.setForeground(new java.awt.Color(51, 51, 51));
        jLDescr.setText("Mensaje:");
        jPanel1.add(jLDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLAsunt.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLAsunt.setForeground(new java.awt.Color(51, 51, 51));
        jLAsunt.setText("Asunto :");
        jPanel1.add(jLAsunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporteVentana dialog = new ReporteVentana(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAsunt;
    private javax.swing.JLabel jLDescr;
    private javax.swing.JLabel jLFech;
    private javax.swing.JLabel jLT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTAsunto;
    private javax.swing.JTextField jTDescr;
    // End of variables declaration//GEN-END:variables

    public void llenarCampos() {

        jLT.setText("REPORTE "+rep.getIdReporte());
        jTAsunto.setText(rep.getAsunto());
        jTDescr.setText(rep.getDescr());
        jLFech.setText(rep.getFech().toString());
        repD.revisarReporte(rep.getIdReporte());
    }

    public Reporte getRep() {
        return rep;
    }

    public void setRep(Reporte rep) {
        this.rep = rep;
    }


}
